apiVersion: v2
name: hybridnet
# When the version is modified, make sure the artifacthub.io/changes list is updated
# Also update CHANGELOG.md
version: 0.1.1
appVersion: 0.4.2
home: https://github.com/alibaba/hybridnet
description: A container networking solution aiming at hybrid clouds.
keywords:
  - network
  - vlan
  - bgp
  - vxlan
  - cni
  - kubernetes
sources:
  - https://github.com/alibaba/hybridnet
type: application
kubeVersion: ">=1.16.0-0"
annotations:
  # Use this annotation to indicate that this chart version is a pre-release.
  artifacthub.io/prerelease: "false"
  # List of changes for the release in artifacthub.io
  artifacthub.io/changes: |
    - "#197 adjust client qps and burst "
    - "#194 mute uselss logging"
    - "#192 fix file exists error while creating pod"
